### ISSUE TITLE
About List_of_EVOBC.json

### ISSUE THREAD

**Issue by loveisp** [RomanticGodVAN/character-Evolution-Dataset#2]
Could you please explain what the values of 'source' and 'era' correspond to in the List_of_EVOBC.json file? I seem to have trouble finding this correspondence. Thank you.

**Comment by RomanticGodVAN** [comment]
“Source”  represents the name of a book or the site from which this font image comes from. ”era“ represents the age or font style of this font image, and the specific content corresponding to the serial number can be seen in the preprint of the paper Axriv

**Comment by loveisp** [comment]
OK. Thanks a lot.

**Comment by loveisp** [comment]
solved
